add style where nodes are displayed using the in-game icons (#2)
* First pass at extract-win-11-stable

* Make desktop window bigger by default

* Add first pass at icons

* Recolor / reshape icons

* Add strokes

* Add guyser icons, revert colors back to originals

* Fiddle with icon size a bit

* Fix win11 extract instructions for 1.2exp

* load resources from encrypted zip file in github actions

---------

Co-authored-by: Konsl <82901383+Konsl@users.noreply.github.com>

diff --git a/.github/workflows/pages.yml b/.github/workflows/pages.yml
--- a/.github/workflows/pages.yml
+++ b/.github/workflows/pages.yml
@@ -24,14 +24,10 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v6
-      - name: download default world data
+      - name: decrypt / extract resources
         env:
-          DEFAULT_WORLD_URL: ${{ secrets.DEFAULT_WORLD_URL }}
-        run: curl -L "$DEFAULT_WORLD_URL" --output "src/default-world.json" && echo "downloaded default-world.json" || echo "could not download default-world.json"
-      - name: download world outline data
-        env:
-          WORLD_OUTLINE_URL: ${{ secrets.WORLD_OUTLINE_URL }}
-        run: curl -L "$WORLD_OUTLINE_URL" --output "src/world-outline.json" && echo "downloaded world-outline.json" || echo "could not download world-outline.json"
+          RESOURCES_PASSPHRASE: ${{ secrets.RESOURCES_PASSPHRASE }}
+        run: bsdtar -xf scripts/resources.encrypted.zip --passphrase "$RESOURCES_PASSPHRASE" -C src && echo "extracted resources" || echo "could not extract resources"
       - name: setup toolchain for wasm
         run: |
           rustup update stable
