use curl instead of wget in workflows

diff --git a/.github/workflows/pages.yml b/.github/workflows/pages.yml
--- a/.github/workflows/pages.yml
+++ b/.github/workflows/pages.yml
@@ -27,7 +27,7 @@ jobs:
       - name: download default world data
         env:
           DEFAULT_WORLD_URL: ${{ secrets.DEFAULT_WORLD_URL }}
-        run: wget -q -O "src/default-world.json" "$DEFAULT_WORLD_URL" && echo "downloaded default-world.json" || echo "could not download default-world.json"
+        run: curl -L "$DEFAULT_WORLD_URL" --output "src/default-world.json" && echo "downloaded default-world.json" || echo "could not download default-world.json"
       - name: setup toolchain for wasm
         run: |
           rustup update stable
diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -23,7 +23,7 @@ jobs:
       - name: download default world data
         env:
           DEFAULT_WORLD_URL: ${{ secrets.DEFAULT_WORLD_URL }}
-        run: wget -q -O "src/default-world.json" "$DEFAULT_WORLD_URL" && echo "downloaded default-world.json" || echo "could not download default-world.json"
+        run: curl -L "$DEFAULT_WORLD_URL" --output "src/default-world.json" && echo "downloaded default-world.json" || echo "could not download default-world.json"
 
       - name: Install stable toolchain
         uses: actions-rs/toolchain@v1
@@ -75,7 +75,7 @@ jobs:
       - name: download default world data
         env:
           DEFAULT_WORLD_URL: ${{ secrets.DEFAULT_WORLD_URL }}
-        run: wget -q -O "src/default-world.json" "$DEFAULT_WORLD_URL" && echo "downloaded default-world.json" || echo "could not download default-world.json"
+        run: curl -L "$DEFAULT_WORLD_URL" --output "src/default-world.json" && echo "downloaded default-world.json" || echo "could not download default-world.json"
 
       - name: Install ${{ matrix.rust }} toolchain
         uses: actions-rs/toolchain@v1
