show outline of the map as background

diff --git a/.github/workflows/pages.yml b/.github/workflows/pages.yml
--- a/.github/workflows/pages.yml
+++ b/.github/workflows/pages.yml
@@ -28,6 +28,10 @@ jobs:
         env:
           DEFAULT_WORLD_URL: ${{ secrets.DEFAULT_WORLD_URL }}
         run: curl -L "$DEFAULT_WORLD_URL" --output "src/default-world.json" && echo "downloaded default-world.json" || echo "could not download default-world.json"
+      - name: download world outline data
+        env:
+          WORLD_OUTLINE_URL: ${{ secrets.WORLD_OUTLINE_URL }}
+        run: curl -L "$WORLD_OUTLINE_URL" --output "src/world-outline.json" && echo "downloaded world-outline.json" || echo "could not download world-outline.json"
       - name: setup toolchain for wasm
         run: |
           rustup update stable
diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -24,6 +24,10 @@ jobs:
         env:
           DEFAULT_WORLD_URL: ${{ secrets.DEFAULT_WORLD_URL }}
         run: curl -L "$DEFAULT_WORLD_URL" --output "src/default-world.json" && echo "downloaded default-world.json" || echo "could not download default-world.json"
+      - name: download world outline data
+        env:
+          WORLD_OUTLINE_URL: ${{ secrets.WORLD_OUTLINE_URL }}
+        run: curl -L "$WORLD_OUTLINE_URL" --output "src/world-outline.json" && echo "downloaded world-outline.json" || echo "could not download world-outline.json"
 
       - name: Install stable toolchain
         uses: actions-rs/toolchain@v1
@@ -82,6 +86,16 @@ jobs:
         env:
           DEFAULT_WORLD_URL: ${{ secrets.DEFAULT_WORLD_URL }}
         run: curl -L "$env:DEFAULT_WORLD_URL" --output "src/default-world.json" && echo "downloaded default-world.json" || echo "could not download default-world.json"
+      - name: download world outline data (non windows)
+        if: matrix.build != 'x86_64-windows'
+        env:
+          WORLD_OUTLINE_URL: ${{ secrets.WORLD_OUTLINE_URL }}
+        run: curl -L "$WORLD_OUTLINE_URL" --output "src/world-outline.json" && echo "downloaded world-outline.json" || echo "could not download world-outline.json"
+      - name: download world outline data (windows)
+        if: matrix.build == 'x86_64-windows'
+        env:
+          WORLD_OUTLINE_URL: ${{ secrets.WORLD_OUTLINE_URL }}
+        run: curl -L "$env:WORLD_OUTLINE_URL" --output "src/world-outline.json" && echo "downloaded world-outline.json" || echo "could not download world-outline.json"
 
       - name: Install ${{ matrix.rust }} toolchain
         uses: actions-rs/toolchain@v1
