load resources from encrypted zip file in github actions

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -20,14 +20,10 @@ jobs:
         uses: actions/checkout@v6
         with:
           submodules: true
-      - name: download default world data
+      - name: decrypt / extract resources
         env:
-          DEFAULT_WORLD_URL: ${{ secrets.DEFAULT_WORLD_URL }}
-        run: curl -L "$DEFAULT_WORLD_URL" --output "src/default-world.json" && echo "downloaded default-world.json" || echo "could not download default-world.json"
-      - name: download world outline data
-        env:
-          WORLD_OUTLINE_URL: ${{ secrets.WORLD_OUTLINE_URL }}
-        run: curl -L "$WORLD_OUTLINE_URL" --output "src/world-outline.json" && echo "downloaded world-outline.json" || echo "could not download world-outline.json"
+          RESOURCES_PASSPHRASE: ${{ secrets.RESOURCES_PASSPHRASE }}
+        run: bsdtar -xf scripts/resources.encrypted.zip --passphrase "$RESOURCES_PASSPHRASE" -C src && echo "extracted resources" || echo "could not extract resources"
 
       - name: Install stable toolchain
         uses: actions-rs/toolchain@v1
@@ -76,26 +72,16 @@ jobs:
         uses: actions/checkout@v6
         with:
           submodules: true
-      - name: download default world data (non windows)
+      - name: decrypt / extract resources (non windows)
         if: matrix.build != 'x86_64-windows'
         env:
-          DEFAULT_WORLD_URL: ${{ secrets.DEFAULT_WORLD_URL }}
-        run: curl -L "$DEFAULT_WORLD_URL" --output "src/default-world.json" && echo "downloaded default-world.json" || echo "could not download default-world.json"
-      - name: download default world data (windows)
+          RESOURCES_PASSPHRASE: ${{ secrets.RESOURCES_PASSPHRASE }}
+        run: bsdtar -xf scripts/resources.encrypted.zip --passphrase "$RESOURCES_PASSPHRASE" -C src && echo "extracted resources" || echo "could not extract resources"
+      - name: decrypt / extract resources (windows)
         if: matrix.build == 'x86_64-windows'
         env:
-          DEFAULT_WORLD_URL: ${{ secrets.DEFAULT_WORLD_URL }}
-        run: curl -L "$env:DEFAULT_WORLD_URL" --output "src/default-world.json" && echo "downloaded default-world.json" || echo "could not download default-world.json"
-      - name: download world outline data (non windows)
-        if: matrix.build != 'x86_64-windows'
-        env:
-          WORLD_OUTLINE_URL: ${{ secrets.WORLD_OUTLINE_URL }}
-        run: curl -L "$WORLD_OUTLINE_URL" --output "src/world-outline.json" && echo "downloaded world-outline.json" || echo "could not download world-outline.json"
-      - name: download world outline data (windows)
-        if: matrix.build == 'x86_64-windows'
-        env:
-          WORLD_OUTLINE_URL: ${{ secrets.WORLD_OUTLINE_URL }}
-        run: curl -L "$env:WORLD_OUTLINE_URL" --output "src/world-outline.json" && echo "downloaded world-outline.json" || echo "could not download world-outline.json"
+          RESOURCES_PASSPHRASE: ${{ secrets.RESOURCES_PASSPHRASE }}
+        run: bsdtar -xf scripts/resources.encrypted.zip --passphrase "$env:RESOURCES_PASSPHRASE" -C src && echo "extracted resources" || echo "could not extract resources"
 
       - name: Install ${{ matrix.rust }} toolchain
         uses: actions-rs/toolchain@v1
